In [1]:
from json import load
import pandas as pd

In [10]:
path = '/Users/samedi/Desktop/tgW.json'

In [11]:
j = load(open(path,'r'))[0]['events']
df = pd.DataFrame(data={
    k: list(map(lambda x: x[k], j)) for k in ["id","class","start","end","summative work time","percentage working"]
})
df.head()

,id,class,start,end,summative work time,percentage working
0,1,экскаватор,0:00:00,0:04:58.743503,0:02:07.032673,42
1,2,подъёмный кран,0:00:00,0:04:58.743503,0:01:08.350913,22
2,3,подъёмный кран,0:00:00,0:04:58.743503,0:00:13.336764,4
3,4,асфальтоукладчик,0:00:00,0:01:02.349369,0:04:04.396192,81
4,5,трактор,0:00:00,0:04:58.743503,0:00:16.004116,5

In [12]:
dfn = {'id': [], 'notes':[]}
for row in j:
    for note in row['notes']:
        dfn['id'].append(row['id'])
        dfn['notes'].append(note)
dfn = pd.DataFrame(dfn)
dfn.head()

   id                        notes
0   1  был в кадре на начало видео
1   1      скрылся за препятствием
2   2  был в кадре на начало видео
3   3  был в кадре на начало видео
4   3      скрылся за препятствием

In [13]:

dfa = {'id': [], 'start':[], 'end':[]}
for row in j:
    for event in row['work events']:
        dfa['id'].append(row['id'])
        dfa['start'].append(event["start work"])
        dfa['end'].append(event["stop work"])
dfa = pd.DataFrame(dfa)
dfa.head()

   id           start             end
0   1  0:00:39.843581  0:00:42.510934
1   1  0:00:58.515050  0:01:01.182403
2   1  0:01:46.527399  0:01:49.194751
3   1  0:02:02.531515  0:02:05.198868
4   1  0:02:37.207100  0:03:03.880627

In [14]:
df.to_csv('tracks.csv')
dfn.to_csv('notes.csv')
dfa.to_csv('events.csv')